### ISSUE TITLE
UI error disables keyboard input after the latest AWM version is loaded.

### ISSUE THREAD

**Issue by maitsukas** [Thal-J/AccurateWorldMap#1]
I am unable to open any menu or move around. Also the highlighted number keeps changing after trying to dismiss the error screen with no end in sight.

![Screenshot_20220523_202946](https://user-images.githubusercontent.com/106106663/169875214-b239516e-be60-4f70-9f15-20840831e6f6.png)

**Comment by Jyndigo** [comment]
Thank you for the issue and for your interest in AWM

Latest version relies on forked versions of two libraries, which haven't been merged & released yet:
1: https://github.com/Thal-J/LibGPS
2: https://github.com/Baertram/LibZone/tree/LibZone_GeoParent

You have to close the game, install those libraries into your addon folder (for LibGPS you have to extract the "src" folder into one called "LibGPS" and replace the LibGPS.txt with the one from the live version) and then reopen the game to stop these errors.

These issues should be fixed for the upcoming beta release, but this github page is the bleeding edge development version, so bugs are expected. Hope this helped

**Comment by Jyndigo** [comment]
I've pushed a patch that disables the player tracking if you don't have the right patches, you can find it here:

https://github.com/Thal-J/AccurateWorldMap/tree/b7aaaab48ffdb090803b1bd900c402e75badd70a
